#!/usr/bin/python
# -*- coding: utf-8 -*-
 
from tkinter import *
 
class Example(Frame):
    def __init__(self, parent):
        Frame.__init__(self, parent, background="#875BA6")
        self.parent = parent
        self.initUI()
    
    def initUI(self):
        self.parent.title("Simple")
        self.pack(fill=BOTH, expand=1)
        
def main():
    root = Tk()
    root.geometry("1024x600")
    app = Example(root)
    root.mainloop()
 
if __name__ == '__main__':
    main()
